### PR TITLE
added line about branch protection

### PR DESCRIPTION
**Pull request by hhoefle1**
Add "Require Conversation resolution before merging"

### CODE REVIEW

**Comment by hhoefle1** [comment]
I have still the adim rights to commit the changes by myself

**Comment by hhoefle1** [comment]
Unblock

**Comment by hhoefle1** [comment]
Comment new

**Comment by ApproverHorst** [comment]
ApproverHorst

**Comment by ApproverHorst** [comment]
ApproverHorst

**Pull request merged**
